"""Add guest workspace and device security tables

Revision ID: 78477282db7e
Revises: fd146b8e6049
Create Date: 2026-07-27 21:57:11.799673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78477282db7e'
down_revision: Union[str, Sequence[str], None] = 'fd146b8e6049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_key', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('guest_name', sa.String(), nullable=True),
    sa.Column('business_type_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['business_type_id'], ['business_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_workspaces_device_id'), 'guest_workspaces', ['device_id'], unique=False)
    op.create_index(op.f('ix_guest_workspaces_id'), 'guest_workspaces', ['id'], unique=False)
    op.create_index(op.f('ix_guest_workspaces_workspace_key'), 'guest_workspaces', ['workspace_key'], unique=True)
    op.create_table('device_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('device_fingerprint', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('screen_width', sa.String(), nullable=True),
    sa.Column('screen_height', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['guest_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_sessions_device_fingerprint'), 'device_sessions', ['device_fingerprint'], unique=True)
    op.create_index(op.f('ix_device_sessions_id'), 'device_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_device_sessions_workspace_id'), 'device_sessions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_sessions_workspace_id'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_id'), table_name='device_sessions')
    op.drop_index(op.f('ix_device_sessions_device_fingerprint'), table_name='device_sessions')
    op.drop_table('device_sessions')
    op.drop_index(op.f('ix_guest_workspaces_workspace_key'), table_name='guest_workspaces')
    op.drop_index(op.f('ix_guest_workspaces_id'), table_name='guest_workspaces')
    op.drop_index(op.f('ix_guest_workspaces_device_id'), table_name='guest_workspaces')
    op.drop_table('guest_workspaces')
    # ### end Alembic commands ###
