"""add tenant scoped unique constraints

Revision ID: 891b13d7735f
Revises: 6a02dbec5b87
Create Date: 2026-07-29 14:01:03.989959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891b13d7735f'
down_revision: Union[str, Sequence[str], None] = '6a02dbec5b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_invoice_number_tenant', 'invoices', ['tenant_id', 'invoice_number'])
    op.create_unique_constraint('uq_order_number_tenant', 'orders', ['tenant_id', 'order_number'])
    op.create_unique_constraint('uq_payment_number_tenant', 'payments', ['tenant_id', 'payment_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_number_tenant', 'payments', type_='unique')
    op.drop_constraint('uq_order_number_tenant', 'orders', type_='unique')
    op.drop_constraint('uq_invoice_number_tenant', 'invoices', type_='unique')
    # ### end Alembic commands ###
