"""make tenant subscription business type nullable

Revision ID: a0d31eca872e
Revises: cb520dc09b01
Create Date: 2026-07-29 18:25:52.853242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d31eca872e'
down_revision: Union[str, Sequence[str], None] = 'cb520dc09b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_subscriptions', 'business_type_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_subscriptions', 'business_type_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
