"""add payment idempotency column

Revision ID: c57e3e835d07
Revises: 891b13d7735f
Create Date: 2026-07-29 14:33:16.975828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57e3e835d07'
down_revision: Union[str, Sequence[str], None] = '891b13d7735f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_request_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_payment_request_id'), 'payments', ['payment_request_id'], unique=False)
    op.create_unique_constraint('uq_payment_request_id_tenant', 'payments', ['tenant_id', 'payment_request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_request_id_tenant', 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_payment_request_id'), table_name='payments')
    op.drop_column('payments', 'payment_request_id')
    # ### end Alembic commands ###
