"""Add welcome CMS settings

Revision ID: ca29e8a066e0
Revises: 78477282db7e
Create Date: 2026-07-27 22:45:44.090687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca29e8a066e0'
down_revision: Union[str, Sequence[str], None] = '78477282db7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('welcome_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('hero_message', sa.Text(), nullable=True),
    sa.Column('faq_content', sa.Text(), nullable=True),
    sa.Column('live_banner', sa.Text(), nullable=True),
    sa.Column('banner_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('welcome_settings')
    # ### end Alembic commands ###
