"""add is_trial to tenant subscriptions

Revision ID: cb520dc09b01
Revises: 87e737e18865
Create Date: 2026-07-29 18:24:28.273691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb520dc09b01'
down_revision: Union[str, Sequence[str], None] = '87e737e18865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subscription_payments_transaction_ref'), 'subscription_payments', ['transaction_ref'], unique=True)
    op.create_foreign_key(None, 'subscription_payments', 'subscription_plans', ['plan_id'], ['id'])
    op.add_column('tenant_subscriptions', sa.Column('is_trial', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_subscriptions', 'is_trial')
    op.drop_constraint(None, 'subscription_payments', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_payments_transaction_ref'), table_name='subscription_payments')
    # ### end Alembic commands ###
