"""feat_phase3_isolated_product_modules

Revision ID: df32dfe00010
Revises: 2f3a86ca41c7
Create Date: 2026-07-08 21:27:07.928471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df32dfe00010'
down_revision: Union[str, Sequence[str], None] = '2f3a86ca41c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(), nullable=False),
    sa.Column('owner_email', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('trial_expires_at', sa.DATETIME(), nullable=True),
    sa.Column('trial_expired', sa.BOOLEAN(), nullable=True),
    sa.Column('subscription_tier', sa.VARCHAR(length=10), nullable=True),
    sa.Column('is_billing_active', sa.BOOLEAN(), nullable=True),
    sa.Column('referral_rewards_usd', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('feature_flags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(), nullable=False),
    sa.Column('feature_name', sa.VARCHAR(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
