CUSTOMER_ADDRESS = "CUSTOMER_ADDRESS"

SALES_CHANNEL = "SALES_CHANNEL"

DELIVERY_STATUS = "DELIVERY_STATUS"

ORDER_FULFILLMENT = "ORDER_FULFILLMENT"


ONLINE_SHOP_CAPABILITIES = [
    CUSTOMER_ADDRESS,
    SALES_CHANNEL,
    DELIVERY_STATUS,
    ORDER_FULFILLMENT,
]
